### ISSUE TITLE
Issues loading module?

### ISSUE THREAD

**Issue by kimboslice99** [RvdHout/IIS-GeoIP2block-Module#7]
Successfully compiled the module, and followed the 'Geoblocker - Manual' however when clicking on the module in IIS it just closes and logs this in event viewer

`IISMANAGER_ERROR_LOADING_PROVIDER_TYPE IIS Manager could not load type 'IisGeoblockModule.GeoblockModuleProvider, IISGeoIP2blockModule, Version=2.4.0.0, Culture=neutral, PublicKeyToken=50262f380b75b73d' for module provider 'Geoblocker' that is declared in %windir%\system32\inetsrv\config\administration.config. Verify that the type is correct, and that the assembly that contains the module provider is in the Global Assembly Cache (GAC). Exception:System.TypeLoadException: Could not load type 'IisGeoblockModule.GeoblockModuleProvider' from assembly 'IISGeoIP2blockModule, Version=2.4.0.0, Culture=neutral, PublicKeyToken=50262f380b75b73d'. at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type) at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName) at System.Type.GetType(String typeName, Boolean throwOnError) at Microsoft.Web.Management.Server.AdministrationModuleProvider.GetModuleProvider(String userName, String connectionName) Process:InetMgr Connection:X53E\X53E`

Any config pointers to get me on the right track?

**Comment by RvdHout** [comment]
I just followed the guide on a VM, no issues whatsoever, so i think you missed a step somewhere

Make sure to use gacutil to register the assembly in the Global Assembly Cache, dragging the file there no longer seems to work

**Comment by kimboslice99** [comment]
I think the confusion lies in the config

the module isnt loaded at all if I use the config exactly as written

`<add name="Geoblocker" type="IisGeoblockModule.GeoblockModuleProvider, IisGeoblockModule, Version=2.2.0.0, Culture=neutral, PublicKeyToken=50262f380b75b73d"/>`

Seems I have to change it like so to get it to load the module

`<add name="Geoblocker" type="IISGeoIP2blockModule.GeoblockModuleProvider, IISGeoIP2blockModule, Version=2.4.0.0, Culture=neutral, PublicKeyToken=50262f380b75b73d" />`

Unsure? please advise

**Comment by RvdHout** [comment]
What documentation are you using? 
Apparently [not this (correct) one](https://github.com/RvdHout/IIS-GeoIP2block-Module/blob/master/docs/Geoblocker%20-%20Manual%20-%20v2.4.pdf),

**Comment by kimboslice99** [comment]
Well thats a good start, thanks!

Still the same issue present however.... Must have compiled wrong, no build errors are present however so im not sure

**Comment by RvdHout** [comment]
With the information given i can only guess you didn't follow the instructions in the documentation exactly as written/explained, maybe some leftovers from the old config?

**Comment by RvdHout** [comment]
One thing to monitor closely, if you copy & paste from the PDF i noticed some lines show some irregularities, eg:

`<add name="Geoblocker" type="IISGeoIP2blockModule.GeoblockHttpModule,IISGeoIP2blockModule,Ver sion=2.4.0.0, Culture=neutral,PublicKeyToken=50262f380b75b73d" preCondition="runtimeVersionv4.0" />`

vs

`<add name="Geoblocker" type="IISGeoIP2blockModule.GeoblockHttpModule,IISGeoIP2blockModule,Version=2.4.0.0, Culture=neutral,PublicKeyToken=50262f380b75b73d" preCondition="runtimeVersionv4.0" />`

eg: the space in. Ver sion, which should read Version

**Comment by RvdHout** [comment]
I fixed the PDF for some weird spacing & line-break issues

**Comment by kimboslice99** [comment]
I've gone over the config quit thoroughly, no leftover mishaps... 

Always seems to log this 
```
Exception Info: System.MissingMethodException
   at IISGeoIP2blockModule.GeoblockModuleService.GetGeoblockConfiguration()
```

Not sure if its VS 2022 thats the issue or if im compiling wrong

**Comment by kimboslice99** [comment]
Compiled with VS 2017, added references, reset config... identical issue, cannot load the module

:anguished:

Thanks anyways

**Comment by kimboslice99** [comment]
@RvdHout, I notice the PDF states under the 6th and 7th page to add the module... but wasn't it added already in the applicationHost.config? after adding it in the applicationHost.config it appears already under modules...?

Either way I still can't make this module work, sadly, things ive checked:

-  tried both debug and release
-  application pools are integrated v4
-  if I specifically deny the client IP address, the client is able to connect fine
-  the imported module is visible under %windir%\Microsoft.NET\assembly\GAC_MSIL\IISGeoIP2blockModule
- running %windir%\system32\inetsrv\appcmd list config -section:system.webServer/geoblockModule results in the expected output

 Any ideas?

**Comment by RvdHout** [comment]
When using debug build you could use [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview) to see what is happening under the hood, eg:

![2022-10-11](https://user-images.githubusercontent.com/13403301/195014840-e332bf7a-13e4-4d1b-b9f2-3656a972b558.png)

![2022-10-11 (1)](https://user-images.githubusercontent.com/13403301/195014871-46d9943d-4c4b-48fd-9eab-8f0e03b74ec1.png)

**Comment by RvdHout** [comment]
I just did a test building it with Visual Studio 2022 and i can confirm i have the exact same error you initially where given... building with Visual Studio 2017 doesn't give this exception.....wow, that is weird!

**Comment by RvdHout** [comment]
It even gets weirder, with Visual Studio 2017, Visual Studio 2019 and Visual Studio 2022 installed side by side, i can upgrade the project to .NET 4.8 and it works even when build with Visual Studio 2022

**Comment by kimboslice99** [comment]
Building on VS 2017, Server 2019, originally had tried VS2022, but due to some of the aforementioned issues I just figured it'd be best to grab VS 2017

Thing is now I'm not seeing any errors anywhere, but I cant seem to make the module function in IIS, the config is exactly as recommended in the pdf

Going to have a look at debugview, doesnt seem to capture any output even after changing the registry key as mentioned <a href="https://stackoverflow.com/questions/33630499/sysinternals-debugview-tool-not-working-in-win-8-1">here</a>, did you need to make registry tweaks to capture?

**Comment by kimboslice99** [comment]
Ya using debug build the only thing I see is this and it only appears once after the webserver starts... settings are pretty much the same, aside from the country
![Capture](https://user-images.githubusercontent.com/94807745/195186069-de5c4208-d6ad-4af2-b649-3991c139ead5.PNG)

**Comment by RvdHout** [comment]
Geez, how hard can it be....

> DebugView (Run as Administrator!) Capture settings:
> 
> * Capture Win32
> * Capture Global Win32
> * Pass Trough
> * Capture Events

Filter on *GeoIP2*

**Comment by RvdHout** [comment]
Have to correct myself, I deleted both IISGeoIP2blockModule.dll's in C:\Windows\System32\inetsrv and the one in C:\Windows\SysWOW64\inetsrv and it still is working, think this is a leftover taken from the original 2.2.0.0 documentation and doesn't seem to be required....bit clueless as of why

**Comment by kimboslice99** [comment]
I did exactly as instructed and saw nothing so I set the filter to just '*' to see what else might be going on...? setting the filter as instructed I see absolutely no output

**Comment by kimboslice99** [comment]
Okay so heres a massive 🤦‍♂️ .NET Extensibility 4.7 is <b>required</b> for this module to work

```
Install-WindowsFeature Web-Net-Ext45 
```
I'm sorry to waste your time RvdHout, but this ought to be added to the documentation


Thank you for assisting in troubleshooting! I greatly appreciate it

**Comment by RvdHout** [comment]
Current sub statuses is based on the way MS implemented it in their Dynamic IP restrictions
https://serverfault.com/questions/659105/what-is-the-meaning-of-an-iis-http-status-code-404-503

**Comment by kimboslice99** [comment]
Ah okay so I suppose that's another leftover from the pdf. (End of page 11)?

Either way working perfectly now, quite pleased... only one curiosity, on the readme it says it uses IPv4 addresses, so does this mean it won't check IPv6 clients or?

**Comment by RvdHout** [comment]
Yeah, i think i might have changed the sub-codes compared to the original module, as the original module had no option to choose the Deny action

It only works for IPv4 i believe (never really tested), it doesn't crash with IPv6 though
https://github.com/RvdHout/IIS-GeoIP2block-Module/pull/3

**Comment by RvdHout** [comment]
As for the .NET Extensibility requirement, sounds kinda obvious if you try to '_extend_' IIS behavior thru modules, handlers and such.... isn't this selected by default if you enable ASP.NET in IIS? (i checked all servers i have access to, those all have this enabled)

**Comment by RvdHout** [comment]
I mainly wrote this to have a development server not completely open to the internet and indexed by google, bing and such.

Anyway is has been a few years since i really worked on this module, so if you create something that can enhance it, please file pull request.

**Comment by RvdHout** [comment]
OK, never have tested this myself t be honest, so thank you!
Take note: The add Allow / Deny rule within the module only accept IPv4 addresses (and masks)

**Comment by RvdHout** [comment]
Tried Visual Studio 2022 again today on a fresh Windows 11 VM, same result as before, no go! 
Seems something or feature is missing from Visual Studio 2022 that both Visual Studio 2017 and Visual Studio 2019 install by default.

**Comment by kimboslice99** [comment]
It would seem the module does indeed have issues with IPv6... setting it to Allow access for 'US' then using the wormly test tool it throws a 403, while setting to to Block access for 'US' it wont throw the 403

Guess its not really comparing the IP to whats in the DB? unsure as of yet

**Comment by kimboslice99** [comment]
@RvdHout Hey there! just updated the module to 2.4.1.0 and IPv6 now seems to work fine! Thanks!
